services:
  - type: web
    name: portfolio
    runtime: java
    buildCommand: cd frontend && npm ci && npm run build && cd ../backend && chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: cd backend && java -Dserver.port=$PORT -jar target/portfolio-backend-0.0.1-SNAPSHOT.jar
    plan: free
    env: production
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: NODE_VERSION
        value: 18
    healthCheckPath: /